title: Smart Home
# Include external resources
resources:
  - url: /community_plugin/vertical-stack-in-card/vertical-stack-in-card.js
    type: js
  - url: /community_plugin/mini-media-player/mini-media-player.js
    type: module
  - url: /community_plugin/mini-graph-card/mini-graph-card-bundle.js
    type: module
  - url: /community_plugin/atomic_calendar/atomic_calendar.js
    type: module
  - url: /community_plugin/compact-custom-header/compact-custom-header.js
    type: module
  - url: /community_plugin/atomic_calendar/atomic_calendar.js
    type: module
  - url: /community_plugin/home-setter/home-setter.js
    type: js
  - url: /community_plugin/group-element/group-element.js
    type: module
  - url: /community_plugin/plan-coordinates/plan-coordinates.js
    type: js
  - url: /community_plugin/lovelace-slider-entity-row/slider-entity-row.js
    type: js

#  - url: /local/my-custom-card.js
#    type: js
#  - url: /local/my-webfont.css
#    type: css

#custom header configuration
cch:
  swipe: true
  swipe_animate: swipe

# Optional background for all views. Check https://developer.mozilla.org/en-US/docs/Web/CSS/background for more examples.
#background: center / cover no-repeat url("/background.png") fixed

# Exclude entities from "Unused entities" view
excluded_entities:
#  - weblink.router
views:
################################################################################################################################
# View tab title.
  - !include userinterface/001_home.yaml
################################################################################################################################          
  - !include userinterface/002_homematic.yaml
################################################################################################################################          
  - !include userinterface/002_homematic_lights.yaml
################################################################################################################################
  - !include userinterface/003_temperatures.yaml
################################################################################################################################
  - !include userinterface/003_humidity.yaml
################################################################################################################################
  - !include userinterface/003_pressure.yaml
################################################################################################################################
  - !include userinterface/003_ventilation.yaml
################################################################################################################################
  - !include userinterface/004_floorplan.yaml 
################################################################################################################################
  - !include userinterface/005_fernando.yaml
################################################################################################################################
  - !include userinterface/005_edgar.yaml
################################################################################################################################
    # Specify a tab icon if you want the view tab to be an icon.
  - !include userinterface/006_media-living.yaml
################################################################################################################################
  - !include userinterface/007_media-bath.yaml
################################################################################################################################
  - !include userinterface/011_wasching.yaml
################################################################################################################################
  - !include userinterface/008_shopping-list.yaml    
################################################################################################################################
  - !include userinterface/009_alarm.yaml   
################################################################################################################################
  - !include userinterface/010_automations.yaml
